service: nuxzieqnul

frameworkVersion: ">=1.78.1 <2.0.0"

provider:
  name: aws
  runtime: python3.7

functions:
  endpoint:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  wsgi:
    app: endpoint.app
    pythonBin: python
  pythonRequirements:
    dockerizePip: false
  customDomain:
    domainName: nuxzieqnul.aws-hknsidwoow.luzi82.com # [BBPMSLSX] end point domain, "nuxzieqnul" part is up to you
    basePath: ''
    createRoute53Record: true
    certificateName: "*.aws-hknsidwoow.luzi82.com" # [BBPMSLSX] domain name set in AWS Certifiicate Manager

plugins:
  - serverless-domain-manager
  - serverless-wsgi
  - serverless-python-requirements
